name: TownyFlight
author: LlmDl
main: com.gmail.llmdlio.townyflight.TownyFlight
version: 1.0.1
depend: [Towny]

commands:
  tfly:
    description: Turns flight on and off
    permission: townyflight.command.tfly
    permission-message: Unable to use command, you don't have <permission>    
  tfly reload
    description: reload the config
    permission: townyflight.command.tfly.reload
    permission-message: Unable to use command, you don't have <permission>

permissions:
  townyflight.command.tfly
    description: User is able to toggle flight on while in their town.
    default: false
  townyflight.command.tfly.reload
    description: User is able to reload the config.
    default: op