name: TownyFlight
author: LlmDl
main: com.gmail.llmdlio.townyflight.TownyFlight
version: 1.2.6
depend: [Towny]

commands:
  tfly:
    description: Turns flight on and off
    aliases: [townyfly, townyflight]
  tfly reload:
    description: reload the config

permissions:
  townyflight.command.tfly:
    description: User is able to toggle flight on while in their town.
    default: op
  townyflight.command.tfly.reload:
    description: User is able to reload the config.
    default: op
  townyflight.bypass:
    description: Bypass permission node for admins to not have their flight disabled while they travel the server.
    default: op
  townyflight.alliedtowns:
    description: Allows players to use /townyflight in towns which are allied to their own.
    default: op