name: TownyFlight
author: LlmDl
main: com.gmail.llmdlio.townyflight.TownyFlight
version: 1.1.0
depend: [Towny]

commands:
  tfly:
    description: Turns flight on and off
  tfly reload:
    description: reload the config

permissions:
  townyflight.command.tfly:
    description: User is able to toggle flight on while in their town.
    default: op
  townyflight.command.tfly.reload:
    description: User is able to reload the config.
    default: op